Tried to fix some problems with the configuration system.
Added the flag slashslashcomment which detects // comments

Made numberous improvements in the buffer overflow checking.  Among other things char array[literal + literal] is now handled correctly.
We also try to handle char array[CONSTANT] where the value of constant is system dependent and not known to LCLint.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -3316,7 +3316,11 @@ test x$myprefix = xNONE && myprefix=$ac_default_prefix
 # cpplib.h defines 2 include dirs; one is $includedir, the other is gcc's
 # include dir.  Not the most portable setup, but let's do our best.
 if test x$ac_cv_c_compiler_gnu = xyes; then
-        GCC_INCLUDE_DIR=`LANGUAGE= LANG= $CC -v 2>&1 | sed -e '/^gcc/ d' -e 's/.* \(.*\)specs/\1include/'`
+
+# This breaks on gcc-3.0 on redhat fixing drl 11-15-2001
+#  GCC_INCLUDE_DIR=`LANGUAGE= LANG= $CC -v 2>&1 | sed -e '/^gcc/ d' -e 's/.* \(.*\)specs/\1include/'`
+ GCC_INCLUDE_DIR=/usr/lib/gcc-lib/i386-linux/2.7.2.1/include
+#  GCC_INCLUDE_DIR=`LANGUAGE= LANG= $CC -v 2>&1 | sed -n -e '/^gcc/ d' -e 's/.* \(.*\)specs/\1include/p'`
 
 cat >>confdefs.h <<EOF
 #define GCC_INCLUDE_DIR "$GCC_INCLUDE_DIR"
@@ -3335,11 +3339,11 @@ cat >>confdefs.h <<EOF
 EOF
 
 cat >>confdefs.h <<EOF
-#define DEFAULT_LARCHPATH ".$PATH_SEPARATOR$myprefix/share/lclint/lib"
+#define DEFAULT_LARCHPATH ".$PATH_SEPARATOR$myprefix/share/lclint/lib$PATH_SEPARATOR`pwd`/lib$PATH_SEPARATOR"
 EOF
 
 cat >>confdefs.h <<EOF
-#define DEFAULT_LCLIMPORTDIR "$myprefix/share/lclint/imports"
+#define DEFAULT_LCLIMPORTDIR "$myprefix/share/lclint/imports$PATH_SEPARATOR`pwd`/imports"
 EOF
 
 # These used to be in herald.h
@@ -3442,7 +3446,7 @@ DEFS=-DHAVE_CONFIG_H
 : ${CONFIG_STATUS=./config.status}
 ac_clean_files_save=$ac_clean_files
 ac_clean_files="$ac_clean_files $CONFIG_STATUS"
-{ echo "$as_me:3445: creating $CONFIG_STATUS" >&5
+{ echo "$as_me:3449: creating $CONFIG_STATUS" >&5
 echo "$as_me: creating $CONFIG_STATUS" >&6;}
 cat >$CONFIG_STATUS <<_ACEOF
 #! $SHELL
@@ -3618,7 +3622,7 @@ cat >>$CONFIG_STATUS <<\EOF
     echo "$ac_cs_version"; exit 0 ;;
   --he | --h)
     # Conflict between --help and --header
-    { { echo "$as_me:3621: error: ambiguous option: $1
+    { { echo "$as_me:3625: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -3637,7 +3641,7 @@ Try \`$0 --help' for more information." >&2;}
     ac_need_defaults=false;;
 
   # This is an error.
-  -*) { { echo "$as_me:3640: error: unrecognized option: $1
+  -*) { { echo "$as_me:3644: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -3689,7 +3693,7 @@ do
   "test/Makefile" ) CONFIG_FILES="$CONFIG_FILES test/Makefile" ;;
   "default-1" ) CONFIG_COMMANDS="$CONFIG_COMMANDS default-1" ;;
   "config.h" ) CONFIG_HEADERS="$CONFIG_HEADERS config.h:config.hin" ;;
-  *) { { echo "$as_me:3692: error: invalid argument: $ac_config_target" >&5
+  *) { { echo "$as_me:3696: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -3939,7 +3943,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:3942: creating $ac_file" >&5
+    { echo "$as_me:3946: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -3957,7 +3961,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:3960: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:3964: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -3970,7 +3974,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:3973: error: cannot find input file: $f" >&5
+           { { echo "$as_me:3977: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -4031,7 +4035,7 @@ for ac_file in : $CONFIG_HEADERS; do test "x$ac_file" = x: && continue
   * )   ac_file_in=$ac_file.in ;;
   esac
 
-  test x"$ac_file" != x- && { echo "$as_me:4034: creating $ac_file" >&5
+  test x"$ac_file" != x- && { echo "$as_me:4038: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
 
   # First look for the input files in the build tree, otherwise in the
@@ -4042,7 +4046,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:4045: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:4049: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -4055,7 +4059,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:4058: error: cannot find input file: $f" >&5
+           { { echo "$as_me:4062: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -4172,7 +4176,7 @@ cat >>$CONFIG_STATUS <<\EOF
   rm -f $tmp/in
   if test x"$ac_file" != x-; then
     if cmp -s $ac_file $tmp/config.h 2>/dev/null; then
-      { echo "$as_me:4175: $ac_file is unchanged" >&5
+      { echo "$as_me:4179: $ac_file is unchanged" >&5
 echo "$as_me: $ac_file is unchanged" >&6;}
     else
       ac_dir=`$as_expr X"$ac_file" : 'X\(.*[^/]\)//*[^/][^/]*/*$' \| \
